version = 1
SPDX-PackageName = "cargo-quality"
SPDX-PackageSupplier = "RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/RAprogramm/cargo-quality"

[[annotations]]
path = ["README.md", ".gitignore", ".rustfmt.toml", "Cargo.lock", "Cargo.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"
