name: CI

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Check
      run: cargo check
    - name: Check formatting
      run: cargo fmt check
    - name: Run tests
      run: cargo test --verbose
